version: '3.8'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - ./tomcat-build:/tmp/tomcat-build
  web:
    image: tomcat
    volumes:
      - ./tomcat-build:/usr/local/tomcat/webapps/
    ports:
      - 8082:8080
